POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title": "test8", 
    "author": "Jack Grealish",
    "url": "http://localhost:3003/api/blogs",
    "likes": 72,
    "userId": "643acb78af56bf9d11755281"
}
